//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace aplicacion_cliente.AlumnosWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ClassroomWSBinding", Namespace="urn:class_api")]
    public partial class ClassroomWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BuscarAlumnoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BienvenidaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EvaluarAlumnoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ClassroomWS() {
            this.Url = global::aplicacion_cliente.Properties.Settings.Default.aplicacion_cliente_AlumnosWS_ClassroomWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BuscarAlumnoCompletedEventHandler BuscarAlumnoCompleted;
        
        /// <remarks/>
        public event BienvenidaCompletedEventHandler BienvenidaCompleted;
        
        /// <remarks/>
        public event EvaluarAlumnoCompletedEventHandler EvaluarAlumnoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ClassroomWS#BuscarAlumno", RequestNamespace="urn:class_api", ResponseNamespace="urn:class_api")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public RespuestaBuscarAlumno BuscarAlumno(string user, string pass, string matricula) {
            object[] results = this.Invoke("BuscarAlumno", new object[] {
                        user,
                        pass,
                        matricula});
            return ((RespuestaBuscarAlumno)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarAlumnoAsync(string user, string pass, string matricula) {
            this.BuscarAlumnoAsync(user, pass, matricula, null);
        }
        
        /// <remarks/>
        public void BuscarAlumnoAsync(string user, string pass, string matricula, object userState) {
            if ((this.BuscarAlumnoOperationCompleted == null)) {
                this.BuscarAlumnoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarAlumnoOperationCompleted);
            }
            this.InvokeAsync("BuscarAlumno", new object[] {
                        user,
                        pass,
                        matricula}, this.BuscarAlumnoOperationCompleted, userState);
        }
        
        private void OnBuscarAlumnoOperationCompleted(object arg) {
            if ((this.BuscarAlumnoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarAlumnoCompleted(this, new BuscarAlumnoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ClassroomWS#Bienvenida", RequestNamespace="urn:class_api", ResponseNamespace="urn:class_api")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public RespuestaBienvenida Bienvenida(string user, string pass, string matricula) {
            object[] results = this.Invoke("Bienvenida", new object[] {
                        user,
                        pass,
                        matricula});
            return ((RespuestaBienvenida)(results[0]));
        }
        
        /// <remarks/>
        public void BienvenidaAsync(string user, string pass, string matricula) {
            this.BienvenidaAsync(user, pass, matricula, null);
        }
        
        /// <remarks/>
        public void BienvenidaAsync(string user, string pass, string matricula, object userState) {
            if ((this.BienvenidaOperationCompleted == null)) {
                this.BienvenidaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBienvenidaOperationCompleted);
            }
            this.InvokeAsync("Bienvenida", new object[] {
                        user,
                        pass,
                        matricula}, this.BienvenidaOperationCompleted, userState);
        }
        
        private void OnBienvenidaOperationCompleted(object arg) {
            if ((this.BienvenidaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BienvenidaCompleted(this, new BienvenidaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ClassroomWS#EvaluarAlumno", RequestNamespace="urn:class_api", ResponseNamespace="urn:class_api")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public RespuestaEvaluarAlumno EvaluarAlumno(string user, string pass, string matricula, int semestre) {
            object[] results = this.Invoke("EvaluarAlumno", new object[] {
                        user,
                        pass,
                        matricula,
                        semestre});
            return ((RespuestaEvaluarAlumno)(results[0]));
        }
        
        /// <remarks/>
        public void EvaluarAlumnoAsync(string user, string pass, string matricula, int semestre) {
            this.EvaluarAlumnoAsync(user, pass, matricula, semestre, null);
        }
        
        /// <remarks/>
        public void EvaluarAlumnoAsync(string user, string pass, string matricula, int semestre, object userState) {
            if ((this.EvaluarAlumnoOperationCompleted == null)) {
                this.EvaluarAlumnoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEvaluarAlumnoOperationCompleted);
            }
            this.InvokeAsync("EvaluarAlumno", new object[] {
                        user,
                        pass,
                        matricula,
                        semestre}, this.EvaluarAlumnoOperationCompleted, userState);
        }
        
        private void OnEvaluarAlumnoOperationCompleted(object arg) {
            if ((this.EvaluarAlumnoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EvaluarAlumnoCompleted(this, new EvaluarAlumnoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:class_api")]
    public partial class RespuestaBuscarAlumno {
        
        private string codeField;
        
        private string messageField;
        
        private string dataField;
        
        private string statusField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:class_api")]
    public partial class RespuestaEvaluarAlumno {
        
        private string codeField;
        
        private string messageField;
        
        private string dataField;
        
        private float promedioField;
        
        private string statusField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public float promedio {
            get {
                return this.promedioField;
            }
            set {
                this.promedioField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:class_api")]
    public partial class RespuestaBienvenida {
        
        private string codeField;
        
        private string messageField;
        
        private string statusField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void BuscarAlumnoCompletedEventHandler(object sender, BuscarAlumnoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarAlumnoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarAlumnoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaBuscarAlumno Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaBuscarAlumno)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void BienvenidaCompletedEventHandler(object sender, BienvenidaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BienvenidaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BienvenidaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaBienvenida Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaBienvenida)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EvaluarAlumnoCompletedEventHandler(object sender, EvaluarAlumnoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EvaluarAlumnoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EvaluarAlumnoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaEvaluarAlumno Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaEvaluarAlumno)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591