//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// Libraries adding
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


// 
// This source code was auto-generated by wsdl, Version=4.8.3928.0.
// 

namespace ClassroomWS_cliente
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "ClassroomWSBinding", Namespace = "urn:class_api")]

    public partial class ClassroomWS : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback BuscarAlumnoOperationCompleted;

        private System.Threading.SendOrPostCallback BienvenidaOperationCompleted;

        private System.Threading.SendOrPostCallback EvaluarAlumnoOperationCompleted;

        /// <remarks/>
        public ClassroomWS()
        {
            this.Url = "http://54.203.246.162/neo/classroom/sw/pruebasclase/alumnos.php";
        }

        /// <remarks/>
        public event BuscarAlumnoCompletedEventHandler BuscarAlumnoCompleted;

        /// <remarks/>
        public event BienvenidaCompletedEventHandler BienvenidaCompleted;

        /// <remarks/>
        public event EvaluarAlumnoCompletedEventHandler EvaluarAlumnoCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ClassroomWS#BuscarAlumno", RequestNamespace = "urn:class_api", ResponseNamespace = "urn:class_api")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public RespuestaBuscarAlumno BuscarAlumno(string user, string pass, string matricula)
        {
            object[] results = this.Invoke("BuscarAlumno", new object[] {
                    user,
                    pass,
                    matricula});
            return ((RespuestaBuscarAlumno)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginBuscarAlumno(string user, string pass, string matricula, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("BuscarAlumno", new object[] {
                    user,
                    pass,
                    matricula}, callback, asyncState);
        }

        /// <remarks/>
        public RespuestaBuscarAlumno EndBuscarAlumno(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((RespuestaBuscarAlumno)(results[0]));
        }

        /// <remarks/>
        public void BuscarAlumnoAsync(string user, string pass, string matricula)
        {
            this.BuscarAlumnoAsync(user, pass, matricula, null);
        }

        /// <remarks/>
        public void BuscarAlumnoAsync(string user, string pass, string matricula, object userState)
        {
            if ((this.BuscarAlumnoOperationCompleted == null))
            {
                this.BuscarAlumnoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarAlumnoOperationCompleted);
            }
            this.InvokeAsync("BuscarAlumno", new object[] {
                    user,
                    pass,
                    matricula}, this.BuscarAlumnoOperationCompleted, userState);
        }

        private void OnBuscarAlumnoOperationCompleted(object arg)
        {
            if ((this.BuscarAlumnoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarAlumnoCompleted(this, new BuscarAlumnoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ClassroomWS#Bienvenida", RequestNamespace = "urn:class_api", ResponseNamespace = "urn:class_api")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public RespuestaBienvenida Bienvenida(string user, string pass, string matricula)
        {
            object[] results = this.Invoke("Bienvenida", new object[] {
                    user,
                    pass,
                    matricula});
            return ((RespuestaBienvenida)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginBienvenida(string user, string pass, string matricula, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("Bienvenida", new object[] {
                    user,
                    pass,
                    matricula}, callback, asyncState);
        }

        /// <remarks/>
        public RespuestaBienvenida EndBienvenida(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((RespuestaBienvenida)(results[0]));
        }

        /// <remarks/>
        public void BienvenidaAsync(string user, string pass, string matricula)
        {
            this.BienvenidaAsync(user, pass, matricula, null);
        }

        /// <remarks/>
        public void BienvenidaAsync(string user, string pass, string matricula, object userState)
        {
            if ((this.BienvenidaOperationCompleted == null))
            {
                this.BienvenidaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBienvenidaOperationCompleted);
            }
            this.InvokeAsync("Bienvenida", new object[] {
                    user,
                    pass,
                    matricula}, this.BienvenidaOperationCompleted, userState);
        }

        private void OnBienvenidaOperationCompleted(object arg)
        {
            if ((this.BienvenidaCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BienvenidaCompleted(this, new BienvenidaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ClassroomWS#EvaluarAlumno", RequestNamespace = "urn:class_api", ResponseNamespace = "urn:class_api")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public RespuestaEvaluarAlumno EvaluarAlumno(string user, string pass, string matricula, [System.Xml.Serialization.SoapElementAttribute(DataType = "integer")] string semestre)
        {
            object[] results = this.Invoke("EvaluarAlumno", new object[] {
                    user,
                    pass,
                    matricula,
                    semestre});
            return ((RespuestaEvaluarAlumno)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginEvaluarAlumno(string user, string pass, string matricula, string semestre, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("EvaluarAlumno", new object[] {
                    user,
                    pass,
                    matricula,
                    semestre}, callback, asyncState);
        }

        /// <remarks/>
        public RespuestaEvaluarAlumno EndEvaluarAlumno(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((RespuestaEvaluarAlumno)(results[0]));
        }

        /// <remarks/>
        public void EvaluarAlumnoAsync(string user, string pass, string matricula, string semestre)
        {
            this.EvaluarAlumnoAsync(user, pass, matricula, semestre, null);
        }

        /// <remarks/>
        public void EvaluarAlumnoAsync(string user, string pass, string matricula, string semestre, object userState)
        {
            if ((this.EvaluarAlumnoOperationCompleted == null))
            {
                this.EvaluarAlumnoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEvaluarAlumnoOperationCompleted);
            }
            this.InvokeAsync("EvaluarAlumno", new object[] {
                    user,
                    pass,
                    matricula,
                    semestre}, this.EvaluarAlumnoOperationCompleted, userState);
        }

        private void OnEvaluarAlumnoOperationCompleted(object arg)
        {
            if ((this.EvaluarAlumnoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EvaluarAlumnoCompleted(this, new EvaluarAlumnoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "urn:class_api")]
    public partial class RespuestaBuscarAlumno
    {

        private string codeField;

        private string messageField;

        private string dataField;

        private string statusField;

        /// <remarks/>
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        public string data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }

        /// <remarks/>
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "urn:class_api")]
    public partial class RespuestaEvaluarAlumno
    {

        private string codeField;

        private string messageField;

        private string statusField;

        private string dataField;

        private float promedioField;

        /// <remarks/>
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        public string data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }

        /// <remarks/>
        public float promedio
        {
            get
            {
                return this.promedioField;
            }
            set
            {
                this.promedioField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "urn:class_api")]
    public partial class RespuestaBienvenida
    {

        private string codeField;

        private string messageField;

        private string statusField;

        /// <remarks/>
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void BuscarAlumnoCompletedEventHandler(object sender, BuscarAlumnoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarAlumnoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal BuscarAlumnoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public RespuestaBuscarAlumno Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaBuscarAlumno)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void BienvenidaCompletedEventHandler(object sender, BienvenidaCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BienvenidaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal BienvenidaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public RespuestaBienvenida Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaBienvenida)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void EvaluarAlumnoCompletedEventHandler(object sender, EvaluarAlumnoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EvaluarAlumnoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal EvaluarAlumnoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public RespuestaEvaluarAlumno Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaEvaluarAlumno)(this.results[0]));
            }
        }
    }
}