//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aplicacion_cliente.Alumnos_WS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:class_api", ConfigurationName="Alumnos_WS.ClassroomWSPortType")]
    public interface ClassroomWSPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ClassroomWS#BuscarAlumno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        aplicacion_cliente.Alumnos_WS.RespuestaBuscarAlumno BuscarAlumno(string user, string pass, string matricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ClassroomWS#BuscarAlumno", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<aplicacion_cliente.Alumnos_WS.RespuestaBuscarAlumno> BuscarAlumnoAsync(string user, string pass, string matricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ClassroomWS#Bienvenida", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        aplicacion_cliente.Alumnos_WS.RespuestaBienvenida Bienvenida(string user, string pass, string matricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ClassroomWS#Bienvenida", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<aplicacion_cliente.Alumnos_WS.RespuestaBienvenida> BienvenidaAsync(string user, string pass, string matricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ClassroomWS#EvaluarAlumno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        aplicacion_cliente.Alumnos_WS.RespuestaEvaluarAlumno EvaluarAlumno(string user, string pass, string matricula, int semestre);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ClassroomWS#EvaluarAlumno", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<aplicacion_cliente.Alumnos_WS.RespuestaEvaluarAlumno> EvaluarAlumnoAsync(string user, string pass, string matricula, int semestre);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:class_api")]
    public partial class RespuestaBuscarAlumno : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        private string dataField;
        
        private string statusField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        public string data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:class_api")]
    public partial class RespuestaEvaluarAlumno : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        private string dataField;
        
        private float promedioField;
        
        private string statusField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        public string data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        /// <remarks/>
        public float promedio {
            get {
                return this.promedioField;
            }
            set {
                this.promedioField = value;
                this.RaisePropertyChanged("promedio");
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:class_api")]
    public partial class RespuestaBienvenida : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        private string statusField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClassroomWSPortTypeChannel : aplicacion_cliente.Alumnos_WS.ClassroomWSPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClassroomWSPortTypeClient : System.ServiceModel.ClientBase<aplicacion_cliente.Alumnos_WS.ClassroomWSPortType>, aplicacion_cliente.Alumnos_WS.ClassroomWSPortType {
        
        public ClassroomWSPortTypeClient() {
        }
        
        public ClassroomWSPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClassroomWSPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClassroomWSPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClassroomWSPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public aplicacion_cliente.Alumnos_WS.RespuestaBuscarAlumno BuscarAlumno(string user, string pass, string matricula) {
            return base.Channel.BuscarAlumno(user, pass, matricula);
        }
        
        public System.Threading.Tasks.Task<aplicacion_cliente.Alumnos_WS.RespuestaBuscarAlumno> BuscarAlumnoAsync(string user, string pass, string matricula) {
            return base.Channel.BuscarAlumnoAsync(user, pass, matricula);
        }
        
        public aplicacion_cliente.Alumnos_WS.RespuestaBienvenida Bienvenida(string user, string pass, string matricula) {
            return base.Channel.Bienvenida(user, pass, matricula);
        }
        
        public System.Threading.Tasks.Task<aplicacion_cliente.Alumnos_WS.RespuestaBienvenida> BienvenidaAsync(string user, string pass, string matricula) {
            return base.Channel.BienvenidaAsync(user, pass, matricula);
        }
        
        public aplicacion_cliente.Alumnos_WS.RespuestaEvaluarAlumno EvaluarAlumno(string user, string pass, string matricula, int semestre) {
            return base.Channel.EvaluarAlumno(user, pass, matricula, semestre);
        }
        
        public System.Threading.Tasks.Task<aplicacion_cliente.Alumnos_WS.RespuestaEvaluarAlumno> EvaluarAlumnoAsync(string user, string pass, string matricula, int semestre) {
            return base.Channel.EvaluarAlumnoAsync(user, pass, matricula, semestre);
        }
    }
}
